version: "3.1"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      # - ./db:/var/opt/mssql 
      - mssql_data:/var/opt/mssql 
      # - ./db/data:/var/opt/mssql/data 
      # - ./db/log:/var/opt/mssql/log 
    environment:
      SA_PASSWORD: "Password!23"
      ACCEPT_EULA: "Y"

volumes:
  mssql_data:
    external: false
